CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(500) NOT NULL,
    author_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY(id),
    CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT uq_author_item UNIQUE(author_id, item_id)
)