CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(50),
    CONSTRAINT pk_booking_item PRIMARY KEY(id),
    CONSTRAINT fk_booking_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_booking_item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT chk_end_after_start CHECK (end_time > start_time),
    CONSTRAINT chk_start_not_past CHECK (start_time >= CURRENT_TIMESTAMP),
    CONSTRAINT chk_start_equal_end CHECK(start_time != end_time)
    );


